with 
CAREPLANS as (
select distinct ENCOUNTER careplan_ENCOUNTER,PATIENT CAREPLAN_PATIENT
from {{ ref('dim_careplans') }}),
MEDICATIONS as ( select distinct ENCOUNTER medication_ENCOUNTER,PATIENT MEDICATION_PATIENT
from {{ ref('fct_medications') }}),
ENCOUNTERS as (select id,PATIENT PATIENT from {{ ref('fct_encounters') }}),
EMCP AS (
select en.id ENCOUNTER_ID ,CP.careplan_ENCOUNTER,M.medication_ENCOUNTER
from ENCOUNTERS en
LEFT JOIN CAREPLANS CP
  ON EN.ID = CP.careplan_ENCOUNTER
 AND EN.PATIENT = CP.CAREPLAN_PATIENT
LEFT JOIN MEDICATIONS M
  ON EN.ID= M.medication_ENCOUNTER
 AND EN.PATIENT = M.MEDICATION_PATIENT)
SELECT ENCOUNTER_ID,careplan_ENCOUNTER,medication_ENCOUNTER,
 (CASE WHEN CAREPLAN_ENCOUNTER IS NOT NULL THEN 1 ELSE 0 END) CP_TAKEN,
 (CASE WHEN MEDICATION_ENCOUNTER IS NOT NULL THEN 1 ELSE 0 END) MP_TAKEN,
 (CASE WHEN CAREPLAN_ENCOUNTER IS NOT NULL AND MEDICATION_ENCOUNTER IS NOT NULL THEN 1 ELSE 0 END) CP_MP_TAKEN_CNT,
 (CASE WHEN CAREPLAN_ENCOUNTER IS NOT NULL AND MEDICATION_ENCOUNTER IS NULL THEN 1 ELSE 0 END) CP_MP_NOT_TAKEN_CNT
 FROM EMCP